# -*- coding: utf-8 -*-
"""ETL_bootcamp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VfqKN820EjOpk9K2O0IE3cCmcQLdCJn_
"""

import pandas as pd
import csv

def organizacao_tabela(base):
  #Leitura da tabela
  df = pd.read_csv(base)
  #Concatenação das colunas de nome
  df['Nome Completo'] = df['Primeiro Nome'] + ' ' + df['Segundo Nome']
  #Renomear a coluna de números como ID
  df.rename(columns={'Número': 'ID'}, inplace = True)
  df.rename(columns={'Valor da Compra': 'Valor Mes'}, inplace = True)
  #Drop das colunas de nome antigas
  df = df.drop('Primeiro Nome', axis = 1)
  df = df.drop('Segundo Nome', axis = 1)
  #Ordenando as linhas de acordo com as compras
  df_ordenado = df.sort_values(by=['Valor Mes'], ascending=False)

  print(f'Valores Ordenados\n\n {df_ordenado}')
  return df_ordenado
#Declarando df como uma variável global
df = organizacao_tabela(base = '/content/Base_ficticia_loja.csv')

#Funções que vão selecionar os primeiros e últimos do df
def selec_top3(organizacao_tabela):
  head3= df.head(3)
  return head3
#declarando como variável global
head3 = selec_top3('/content/Base_ficticia_loja.csv')

def selec_last3(organizacao_tabela):
  tail3= df.tail(3)
  return tail3
#declarando como variável global
tail3 = selec_last3('/content/Base_ficticia_loja.csv')

#Textos para mensagens como variável global, afim de economizar espaço e trabalho nas próximas funções
texto_top3 = 'você está entre nossos principais clientes, por isso, estamos lhe oferecendo um cartão fidelidade da nossa loja! Sem custo algum, entre em contato com nosso suporte para obter os benefícios!'
texto_last3 ='esta mensagem lhe concede um cumpom de desconto progressivo de até 40% off em qualquer compra em nossa loja! Não deixe de aproveitar a oportunidade!'

#Geração dos textos como itens de lista
def geracao_top3(head3):
  final_top3 = []
  for primeiros in head3['Nome Completo']:
    final_top3.append(f'Olá {primeiros}! {texto_top3}')
  return final_top3
 #o retorno é a lista
print("")
def geracao_last3(tail3):
  final_last3 = []
  for ultimos in tail3['Nome Completo']:
    final_last3.append(f'Olá {ultimos}! {texto_last3}')
  return final_last3
  #o retorno é a lista

#Funções de Geração dos arquivos csv
def csv_top3 (geracao_top3):
  #Por conta dos acentos, foi necessário utilizar um encoding específico, uma vez que o utf-8 não era capaz de tal
  with open ('top3.csv', 'w',newline = '', encoding = 'ISO-8859-1') as file:
    writer = csv.writer(file)
    #Estrutura de repetição para criar linhas, onde cada linha é um valor da lista
    for i in range(3):
      writer.writerow([geracao_top3[i-1]])
    return True
#Mesmas técnicas usadas acima
def csv_last3(geracao_last3):
  with open ('last3.csv', 'w',newline = '', encoding = 'ISO-8859-1') as file:
    writer = csv.writer(file)
    for i in range(3):
      writer.writerow([geracao_last3[i-1]])
    return True

csv_top3(geracao_top3(head3))
csv_last3(geracao_last3(tail3))

